# Generated by Django 4.0.6 on 2022-07-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstaWork_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
