# Generated by Django 4.0.6 on 2022-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaWork_App', '0003_user_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='regular', max_length=10),
        ),
    ]
